export const words = [
  { id: 1, english: "hello", spanish: "hola" },
  { id: 2, english: "goodbye", spanish: "adios" },
  { id: 3, english: "please", spanish: "por favor" },
  { id: 4, english: "thank you", spanish: "gracias" },
  { id: 5, english: "excuse me", spanish: "permiso" },
  { id: 6, english: "yes", spanish: "sí" },
  { id: 7, english: "no", spanish: "no" },
  { id: 8, english: "friend", spanish: "amigo" },
  { id: 9, english: "family", spanish: "familia" },
  { id: 10, english: "love", spanish: "amor" },
  { id: 11, english: "happiness", spanish: "felicidad" },
  { id: 12, english: "sadness", spanish: "tristeza" },
  { id: 13, english: "angry", spanish: "enojado" },
  { id: 14, english: "fear", spanish: "miedo" },
  { id: 15, english: "surprise", spanish: "sorpresa" },
  { id: 16, english: "joy", spanish: "alegría" },
  { id: 17, english: "pain", spanish: "dolor" },
  { id: 18, english: "hope", spanish: "esperanza" },
  { id: 19, english: "despair", spanish: "desesperación" },
  { id: 20, english: "anxiety", spanish: "ansiedad" },
  { id: 21, english: "wallet", spanish: "billetera" },
  { id: 22, english: "doubt", spanish: "duda" },
  { id: 23, english: "trust", spanish: "confianza" },
  { id: 24, english: "mistake", spanish: "error" },
  { id: 25, english: "success", spanish: "éxito" },
  { id: 26, english: "failure", spanish: "fracaso" },
  { id: 27, english: "courage", spanish: "valentía" },
];
